---
- hosts: clients
  gather_facts: no
  tasks:
    - name: Kill clients
      shell: killall -s INT hotstuff-client
      ignore_errors: yes

- hosts: replicas
  gather_facts: no
  tasks:
    - name: Kill servers
      shell: killall -s INT hotstuff-app
      ignore_errors: yes
