---
- hosts: clients
  gather_facts: no
  tasks:
    - name: Clean results dir
      file:
        path: /tmp/results
        state: absent
    - name: Create results dir
      file:
        path: /tmp/results
        state: directory

- hosts: replicas
  gather_facts: no
  vars:
    batch_size: 100
    view_change: 100
  tasks:
    - name: Start servers
      shell: >
        ./hotstuff-app
        --conf "$HOME/self_config.conf"
        --block-size {{ batch_size }}
      async: 1000
      poll: 0

- hosts: clients
  gather_facts: no
  vars:
    rate: 10000
    time: 60
    payload: 0
    num_clients: 1
    client_id: "{{ inventory_hostname | regex_replace('[^0-9]', '') }}"
  tasks:
    - name: Start clients
      shell: >
        ./hotstuff-client
        --cid {{ item }}
        --iter -1
        --max-async 3200
        --request-rate {{ rate }}
        2> "/tmp/results/{{ inventory_hostname }}-c{{ item }}.out"
      async: 1000
      poll: 0
      loop: "{{ range((client_id|int) * (num_clients|int) - (num_clients|int), (client_id|int) * (num_clients|int)) | list }}"
      register: hotstuff_clients

    - name: Sleep
      shell: sleep "{{ time }}"
      async: 1000
      poll: 0
      register: hotstuff_wait

    - name: Wait for benchmark to run
      async_status:
        jid: "{{ hotstuff_wait.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
    
    - name: Kill clients
      shell: killall -s INT hotstuff-client
      ignore_errors: yes

    - name: Wait for benchmark to run
      async_status:
        jid: "{{ item.ansible_job_id }}"
      loop: "{{ hotstuff_clients.results }}"
      register: job_result
      until: job_result.finished
      retries: 30

- hosts: replicas
  gather_facts: no
  tasks:
    - name: Kill servers
      shell: killall -s INT hotstuff-app
      ignore_errors: yes

- hosts: clients
  gather_facts: no
  tasks:
    - name: Fetch data
      synchronize:
        src: "/tmp/results/"
        dest: "{{ destdir }}/{{ inventory_hostname }}"
        mode: pull
